[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --strict-markers
    --tb=short
    --disable-warnings
markers =
    asyncio: mark test as async
    integration: mark test as integration test
    slow: mark test as slow running
asyncio_mode = auto

[pytest]
filterwarnings =
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning
    ignore:builtin type .* has no __module__ attribute:DeprecationWarning 